"""AI curriculum generation (Sprint 11).

Turns a track + placement level into a full course — a syllabus of lessons, each
with exercises and a quiz — generated by the AI provider and written into the
existing content tables (marked ``source="ai"``), so serving, grading, "Today",
and progress work unchanged. The heavy work runs in a background job; this
service both starts the job and performs the generation (called by the worker).
"""

from __future__ import annotations

import re
import time
import uuid
from collections.abc import Callable
from typing import Any

from app.application.ports.ai_provider import (
    AIProvider,
    AIProviderError,
    AIQuotaError,
    GeneratedLessonBatch,
    GenerateLessonBatchRequest,
)
from app.application.services.ai_usage import AIUsageGuard
from app.application.services.execution_service import ExecutionService
from app.application.services.progress_service import completed_item_ids
from app.core.config import Settings
from app.core.logging import get_logger
from app.domain.entities import Course, GenerationJob, Lesson
from app.domain.repositories import (
    CourseRepository,
    ExerciseRepository,
    GenerationJobRepository,
    LanguageRepository,
    LanguageTrackRepository,
    LessonRepository,
    ProgressRepository,
    QuizRepository,
)

logger = get_logger(__name__)

_ACTIVE_STATES = {"pending", "running"}


def _slug(text: str) -> str:
    base = re.sub(r"[^a-z0-9]+", "-", (text or "").lower()).strip("-") or "item"
    return f"{base[:48]}-{uuid.uuid4().hex[:6]}"


class CurriculumService:
    def __init__(
        self,
        provider: AIProvider,
        jobs: GenerationJobRepository,
        courses: CourseRepository,
        lessons: LessonRepository,
        exercises: ExerciseRepository,
        quizzes: QuizRepository,
        languages: LanguageRepository,
        tracks: LanguageTrackRepository,
        execution: ExecutionService,
        usage: AIUsageGuard,
        settings: Settings,
        progress: ProgressRepository,
    ) -> None:
        self._provider = provider
        self._jobs = jobs
        self._courses = courses
        self._lessons = lessons
        self._exercises = exercises
        self._quizzes = quizzes
        self._languages = languages
        self._tracks = tracks
        self._execution = execution
        self._usage = usage
        self._settings = settings
        self._progress = progress

    # ----- job control -----

    def start_generation(self, *, user_id: uuid.UUID, track_id: uuid.UUID) -> GenerationJob:
        track = self._tracks.get_by_id(track_id)
        if track is None or track.user_id != user_id:
            raise LookupError(f"Track {track_id} not found")
        latest = self._jobs.get_latest_for_track(track_id)
        if latest is not None and latest.status in _ACTIVE_STATES:
            return latest  # a generation is already in flight
        return self._jobs.create(
            track_id=track_id, user_id=user_id, total=self._settings.curriculum_lesson_count
        )

    def list_courses(self, user_id: uuid.UUID):
        """The learner's own (track-scoped) courses."""
        track_ids = [t.id for t in self._tracks.list_by_user(user_id)]
        return self._courses.list_by_track_ids(track_ids)

    def get_status(self, *, user_id: uuid.UUID, track_id: uuid.UUID) -> GenerationJob:
        track = self._tracks.get_by_id(track_id)
        if track is None or track.user_id != user_id:
            raise LookupError(f"Track {track_id} not found")
        job = self._jobs.get_latest_for_track(track_id)
        if job is None:
            raise LookupError("No generation job for this track")
        return job

    # ----- continuous learning: extend an existing course (Sprint 12) -----

    def get_owned_course(self, *, course_id: uuid.UUID, user_id: uuid.UUID) -> Course:
        """Return the course only if it belongs to one of the learner's tracks.

        Raises ``LookupError`` when the course does not exist or is not owned by
        the user (we don't distinguish, to avoid leaking others' course ids).
        """
        course = self._courses.get_by_id(course_id)
        if course is None or course.track_id is None:
            raise LookupError("Course not found")
        track = self._tracks.get_by_id(course.track_id)
        if track is None or track.user_id != user_id:
            raise LookupError("Course not found")
        return course

    def course_completion(
        self, *, course_id: uuid.UUID, user_id: uuid.UUID
    ) -> tuple[int, int, int]:
        """Return ``(completed, total, percent)`` items for this learner's course."""
        done = completed_item_ids(self._progress.list_for_user(user_id))
        total = 0
        completed = 0
        for lesson in self._lessons.list_by_course(course_id):
            total += 1
            completed += 1 if lesson.id in done["lesson"] else 0
            for ex in self._exercises.list_by_lesson(lesson.id):
                total += 1
                completed += 1 if ex.id in done["exercise"] else 0
            for qz in self._quizzes.list_by_lesson(lesson.id):
                total += 1
                completed += 1 if qz.id in done["quiz"] else 0
        percent = round(completed / total * 100) if total else 0
        return completed, total, percent

    def can_extend(self, *, course_id: uuid.UUID, user_id: uuid.UUID) -> bool:
        """Whether the "Learn more" hint should show (course near completion)."""
        _, total, percent = self.course_completion(course_id=course_id, user_id=user_id)
        return total > 0 and percent >= round(self._settings.curriculum_extend_threshold * 100)

    def lesson_count(self, course_id: uuid.UUID) -> int:
        return len(self._lessons.list_by_course(course_id))

    def clamp_extend_count(self, count: int | None) -> int:
        """Bound a requested lesson count to [1, curriculum_extend_max]."""
        if count is None:
            count = self._settings.curriculum_extend_count
        return max(1, min(int(count), self._settings.curriculum_extend_max))

    def extend_course(
        self,
        *,
        course_id: uuid.UUID,
        user_id: uuid.UUID,
        focus: str | None = None,
        count: int | None = None,
    ) -> list[Lesson]:
        """Append ``count`` lessons (each with exercises + a quiz) to an owned course.

        ``focus`` is the learner's request — a specific subject or a short chat
        transcript — which the generator uses to target the new lessons (and to
        resolve vague follow-ups like "more" against the recent conversation).
        Without a focus the syllabus is simply continued. Ownership and the
        per-user AI budget are enforced. Returns the newly created lessons.
        """
        course = self.get_owned_course(course_id=course_id, user_id=user_id)
        # Enforce the per-user AI budget before spending a generation call.
        self._usage.check(user_id)
        track = self._tracks.get_by_id(course.track_id)
        language = self._languages.get_by_id(course.language_id)
        if track is None or language is None:
            raise LookupError("Course not found")
        level = (track.level if track else None) or "beginner"

        existing = self._lessons.list_by_course(course_id)
        order_index = max((ln.order_index for ln in existing), default=-1) + 1
        prior_titles = [ln.title for ln in existing]

        count = self.clamp_extend_count(count)
        batch = self._generate_batch_with_retry(
            language, level, count, prior_titles, user_id, focus=focus or ""
        )
        lesson_dicts = (batch.lessons if batch else [])[:count]

        created: list[Lesson] = []
        for data in lesson_dicts:
            lesson = self._build_lesson_from_data(course.id, language, order_index, data)
            created.append(lesson)
            order_index += 1
        logger.info(
            "curriculum: extended course=%s by %d lesson(s) focus=%r",
            course_id,
            len(created),
            (focus or "")[:60],
        )
        return created

    # ----- generation (run by the background worker) -----

    def generate_course(
        self, job_id: uuid.UUID, *, commit: Callable[[], None] = lambda: None
    ) -> None:
        job = self._jobs.get_by_id(job_id)
        if job is None:
            return
        track = self._tracks.get_by_id(job.track_id)
        language = self._languages.get_by_id(track.language_id) if track else None
        if track is None or language is None:
            self._jobs.update(job_id, status="error", error="Track or language missing")
            commit()
            return

        level = track.level or "beginner"
        try:
            self._jobs.update(job_id, status="running")
            commit()
            course = self._courses.create(
                language_id=language.id,
                track_id=track.id,
                title=f"{language.name} — {level.capitalize()}",
                slug=_slug(f"{language.slug}-{level}"),
                description=f"A personalized {level} {language.name} course.",
            )
            self._jobs.update(job_id, course_id=course.id)
            commit()
        except Exception as exc:  # noqa: BLE001
            logger.exception("Curriculum setup failed for job %s", job_id)
            self._jobs.update(job_id, status="error", error=str(exc)[:500])
            commit()
            return

        total = self._settings.curriculum_lesson_count
        batch_size = max(1, self._settings.curriculum_batch_size)
        pause = self._settings.curriculum_batch_pause_seconds
        logger.info(
            "curriculum: start job=%s course='%s' level=%s lessons=%d (batch=%d)",
            job_id,
            course.title,
            level,
            total,
            batch_size,
        )

        completed = 0
        order_index = 0
        prior_titles: list[str] = []
        remaining = total
        while remaining > 0:
            count = min(batch_size, remaining)
            logger.info(
                "curriculum: batch of %d (lessons %d-%d/%d)",
                count,
                completed + 1,
                completed + count,
                total,
            )
            batch = self._generate_batch_with_retry(
                language, level, count, prior_titles, job.user_id
            )
            for lesson_data in (batch.lessons if batch else [])[:count]:
                lesson = self._build_lesson_from_data(
                    course.id, language, order_index, lesson_data
                )
                prior_titles.append(lesson.title)
                order_index += 1
                completed += 1
                # Publish lessons as each batch lands (incremental progress).
                self._jobs.update(job_id, completed=completed)
                commit()
            remaining -= count
            if remaining > 0 and pause > 0:
                logger.info("curriculum: pausing %.0fs before next batch", pause)
                time.sleep(pause)

        self._jobs.update(job_id, status="done")
        commit()
        logger.info("curriculum: done job=%s (%d/%d lessons)", job_id, completed, total)

    def _generate_batch_with_retry(
        self,
        language,  # noqa: ANN001 - domain entity
        level: str,
        count: int,
        prior_titles: list[str],
        user_id: uuid.UUID,
        focus: str = "",
    ) -> GeneratedLessonBatch | None:
        """Generate one batch of lessons, retrying on rate-limit; None on failure."""
        attempts = max(1, self._settings.curriculum_retry_attempts)
        for attempt in range(attempts):
            try:
                batch = self._provider.generate_lesson_batch(
                    GenerateLessonBatchRequest(
                        language=language.slug,
                        level=level,
                        count=count,
                        exercise_count=self._settings.curriculum_exercises_per_lesson,
                        quiz_question_count=self._settings.curriculum_quiz_questions,
                        prior_titles=prior_titles,
                        focus=focus,
                    )
                )
                self._usage.record(
                    user_id, kind="generate", model=batch.model, total_tokens=batch.total_tokens
                )
                return batch
            except AIQuotaError as exc:
                if attempt < attempts - 1:
                    delay = max(
                        self._settings.curriculum_retry_delay_seconds, exc.retry_after or 0
                    )
                    delay = min(delay, 90.0)
                    logger.warning(
                        "curriculum: rate-limited, waiting %.0fs (attempt %d/%d)",
                        delay,
                        attempt + 1,
                        attempts,
                    )
                    time.sleep(delay)
                else:
                    logger.warning("curriculum: giving up on a batch after rate limits")
            except AIProviderError:
                # Malformed JSON / empty / transient provider error — regenerate.
                if attempt < attempts - 1:
                    logger.warning(
                        "curriculum: batch response unusable, retrying (attempt %d/%d)",
                        attempt + 1,
                        attempts,
                    )
                    time.sleep(3)
                else:
                    logger.warning("curriculum: giving up on a batch after bad responses")
            except Exception:  # noqa: BLE001 - skip this batch, keep going
                logger.exception("Curriculum batch generation failed")
                return None
        return None

    def _build_lesson_from_data(
        self,
        course_id: uuid.UUID,
        language,  # noqa: ANN001 - domain entity
        order_index: int,
        data: dict[str, Any],
    ) -> Lesson:
        """Persist one generated lesson (content + exercises + quiz); return it."""
        title = str(data.get("title", f"Lesson {order_index + 1}"))
        lesson = self._lessons.create(
            course_id=course_id,
            title=title,
            slug=_slug(title),
            order_index=order_index,
            content=str(data.get("content", "")),
            source="ai",
        )
        exercises = data.get("exercises") if isinstance(data.get("exercises"), list) else []
        for ex in exercises:
            self._build_exercise(lesson.id, language.slug, title, ex)
        quiz = data.get("quiz") if isinstance(data.get("quiz"), dict) else {}
        self._build_quiz(lesson.id, title, quiz)
        logger.info(
            "curriculum:   built '%s' (%d chars, %d exercises, %d quiz Qs)",
            title,
            len(str(data.get("content", ""))),
            len(exercises),
            len((quiz or {}).get("questions", [])),
        )
        return lesson

    def _build_exercise(
        self, lesson_id: uuid.UUID, language: str, topic: str, ex: dict[str, Any]
    ) -> None:
        test_spec = ex.get("test_spec") or {}
        # Optional self-verify: advisory only — a failing reference (common with
        # lighter models whose test_spec is slightly off) is logged, not dropped,
        # so lessons always keep their exercises.
        if self._settings.curriculum_self_verify and test_spec.get("cases"):
            verdict, _ = self._execution.grade(
                code=str(ex.get("reference_solution", "")), language=language, test_spec=test_spec
            )
            if verdict != "passed":
                logger.warning(
                    "curriculum: exercise '%s' failed self-verify (%s); keeping anyway",
                    ex.get("title", topic),
                    verdict,
                )
        self._exercises.create(
            lesson_id=lesson_id,
            language=language,
            title=str(ex.get("title", topic)),
            slug=_slug(str(ex.get("title", topic))),
            prompt=str(ex.get("prompt", "")),
            starter_code=str(ex.get("starter_code", "")),
            test_spec=test_spec,
            source="ai",
        )

    def _build_quiz(self, lesson_id: uuid.UUID, topic: str, quiz: dict[str, Any]) -> None:
        questions = quiz.get("questions") or []
        if not questions:
            return
        model = self._quizzes.create(
            lesson_id=lesson_id,
            title=str(quiz.get("title", f"{topic} check")),
            slug=_slug(f"{topic}-quiz"),
            description=None,
        )
        for i, q in enumerate(questions):
            choices = [
                {"text": str(c.get("text", "")), "is_correct": bool(c.get("is_correct"))}
                for c in (q.get("choices") or [])
            ]
            if len(choices) >= 2 and any(c["is_correct"] for c in choices):
                self._quizzes.add_question(
                    quiz_id=model.id,
                    prompt=str(q.get("prompt", "")),
                    type="single",
                    order_index=i,
                    choices=choices,
                )
